defaults:
  - _self_
  - override hydra/hydra_logging: disabled
  - override hydra/job_logging: disabled

hydra:
  output_subdir: null
  run:
    dir: .

tokenizer:
  dir: 'spm_artifacts'
  model_prefix: 'sp_bpe_512'

train:
  dataset:
    data: 'materials/train_nlfi.txt'
    n_lines: 8
  dataloader:
    batch_size: 16

eval:
  dataset:
    data: 'materials/eval_nlfi.txt'
    n_lines: ${train.dataset.n_lines}
  dataloader:
    batch_size: ${train.dataloader.batch_size}

loggers:
  tensorboard:
    dir: 'tb_logs'
    subdir: 'grulm'

model:
  hidden_dim: 512

trainer:
  learning_rate: 1e-3
  max_epoch: 20
