defaults:
  - base_train_config

loggers:
  tensorboard:
    dir: 'tb_logs'
    subdir: 'transformer'

train:
  dataset:
    data: 'materials/train_nlfi.txt'
    n_tokens: 512
  dataloader:
    batch_size: 32

model:
  hidden_dim: 128

eval:
  dataset:
    data: 'materials/eval_nlfi.txt'
    n_tokens: ${train.dataset.n_tokens}
  dataloader:
    batch_size: ${train.dataloader.batch_size}

trainer:
  learning_rate: 3e-4
  max_epoch: 60